# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
workflow_dispatch:
  schedule:
    - cron: '53 12 * * *'

jobs:
   build:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run application
        
        run: python -u main.py
